#注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#服务配置
server:
  port: 9090
#spring配置
spring:
  #1.应用配置
  application:
    name: h-gateway #指定服务名
  redis:
    host: 192.168.2.111
    port: 6379
    
#配置路由规则
zuul:
  routes:
    #路由id,随便写
    ihrm-company:
      path: /company/** #需要映射的路径地址
      #url: http://127.0.0.1:9001 #映射路径对应的实际微服务的url路径
      serviceId: ihrm-company
      #zuul 自动的会删除请求的前缀 http://127.0.0.1:9001/company
      stripPrefix: false #不删除请求前缀
      #处理敏感头信息
      sentiviteHeaders:   #将指定路由的敏感头设置为空
      customSensitiveHeaders: true #对指定路由开启自定义敏感头
